### ISSUE TITLE
sqd init polygon-squid --template evm throwing error

### ISSUE THREAD

**Issue by farazahmadvaival** [subsquid/squid-cli#42]
I have to create new squid project using evm chain. when i run this command
```
sqd init polygon-squid --template evm
```
I am getting this error:

`
Error: Unknown server error. Please check that your are using the latest version of the Squid CLI.
`

**Comment by octo-gone** [comment]
Hey! Please try again, we had small downtime now it is up. If problem remains please comment, else close it. Thank you!
