### ISSUE TITLE
`typegen` exiting `EOENT`

### ISSUE THREAD

**Issue by dangerousfood** [subsquid/squid-cli#50]
Replication steps:
```
node --version
v18.17.1

sqd --version
@subsquid/cli/2.5.0 darwin-arm64 node-v18.17.1
```

```
 sqd typegen --help
TYPEGEN
    Error: spawn squid-evm-typegen ENOENT
    Code: ENOENT
```

This issue seems to occur whether I am in a subsquid directory or not, I have tried multiple versions of node and multiple versions of subsquid/cli

**Comment by octo-gone** [comment]
Hello! Did you try to install dependencies of the project, `npm ci`? You can also install `squid-evm-typegen` separately using following command `npm i @subsquid/evm-typegen`.

**Comment by dangerousfood** [comment]
Yes installing `npm install -g  @subsquid/evm-typegen@latest` seems to work
