### ISSUE TITLE
Implement .squidignore

### ISSUE THREAD

**Issue by belopash** [subsquid/squid-cli#71]

**Comment by mlenser** [comment]
This would be super helpful. Currently we're having to delete large amount of code from our monorepo to get a deploy to work.

**Comment by belopash** [comment]
@mlenser `.squidignore` is available in @subsquid/cli@2.9.0-beta.1. It follows `.gitignore` [spec](https://git-scm.com/docs/gitignore).
Please try it out 🙂

**Comment by mlenser** [comment]
It appears to work!

For our monorepo we had to add it to both the root and the indexer package for it to work. Or at least the indexer package even though the command was run from root.
But all good.
Thank you!

**Comment by belopash** [comment]
> For our monorepo we had to add it to both the root and the indexer package for it to work. Or at least the indexer package even though the command was run from root. But all good. Thank you!

Yep, it's intendend behaviour. But why do you need to add it both to root and to package itself? Why not to root only?
